name: Bug report
description: Create a report to help us improve
labels: [bug]
body:

- type: textarea
  attributes:
    label: Describe the bug
    description: A concise description of what you're experiencing.
  validations:
    required: true

- type: textarea
  attributes:
    label: Integration state attributes 
    value: |
      ```yaml
        [PASTE STATE ATTRIBUTES HERE]
      ```
    description: |
      If applicable, please add state attributes of your integration in YAML
      
      [![Open your Home Assistant instance and show your state developer tools.](https://my.home-assistant.io/badges/developer_states.svg)](https://my.home-assistant.io/redirect/developer_states/)

- type: textarea
  attributes:
    label: Screenshots
    description: |
     Please add screenshots to help us to diagnose the issue:
      - screenshots of card in your Lovelace
      - if it's error card [it looks like that](https://i.imgur.com/8COQUeo.png) please also
      provide screenshot from you's browser console showing the error
  validations:
    required: true

- type: markdown
  attributes:
    value: "## Environment"

- type: markdown
  attributes:
    value: |
      Please provide information about current configuration that you are using.

- type: input
  attributes:
    label: Card version
    description: Current card version that you are using e.g. 1.1.0 ("latest" is not valid)
    placeholder: v1.1.0
  validations:
    required: true

- type: dropdown
  attributes:
    label: Installation type
    options:
      - Home Assistant Community Store (HACS)
      - Manual
      - Other

  validations:
    required: true

- type: textarea
  attributes:
    label: Card Configuration
    description: |
      Please provide your Meteoalarm Card configuration in Dashboard
    value: |
      ```yaml
      [PASTE CONFIGURATION HERE]
      ```
  validations:
    required: true

- type: dropdown
  attributes:
    label: Integration type
    options:
      - Meteoalarm
      - Météo-France
      - Environnement Canada
      - Deutscher Wetterdienst (DWD)
      - NINA
      - Burze.dzis.net
      - weatheralerts
      - Other
  validations:
    required: true

- type: dropdown
  attributes:
    label: Integration configuration
    options:
      - YAML (configuration.yaml)
      - GUI
      - Other

- type: textarea
  attributes:
    label: Integration Configuration
    description: |
      If you have configured integration with YAML - Please provide your integration
      configuration from `configuration.yaml`.
    value: |
      ```yaml
      [PASTE CONFIGURATION HERE]
      ```
  validations:
    required: false
