name: Validate Translations

on: [push, pull_request]

jobs:
  json-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Validate JSONs
        uses: nhalstead/validate-json-action@0.1.3
        env:
          INPUT_SCHEMA: src/translations/schema.json
          INPUT_JSONS: "src/translations/*.json
