name: Validate Translations

on: [push, pull_request]

jobs:
  json-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Validate JSONs
        uses: nhalstead/validate-json-action@0.1.3
        with:
          schema: src/translations/schema/schema.json
          jsons: src/translations/*.json
