name: HACS validation

on:
  push:
    branches:
    - master

jobs:
  validate:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - name: Validate
        uses: "hacs/action@main"
        with:
          category: "plugin"
